[project]
name = "ooni-zapret-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astroid==4.0.4",
    "certifi==2026.4.22",
    "charset-normalizer==3.4.7",
    "dill==0.4.1",
    "idna==3.15",
    "isort==8.0.1",
    "mccabe==0.7.0",
    "numpy==2.4.4",
    "pandas==3.0.3",
    "platformdirs==4.9.6",
    "pylint==4.0.5",
    "python-dateutil==2.9.0.post0",
    "requests==2.34.0",
    "six==1.17.0",
    "tomlkit==0.15.0",
    "urllib3==2.7.0",
]
